AnimationData:
  BlueFire: ~
  Water:
    Water:
      AnimSpeed: 5
      Clips:
        -
          - 0
          - 0
          - 16
          - 16
        -
          - 16
          - 0
          - 16
          - 16
        -
          - 32
          - 0
          - 16
          - 16
        -
          - 48
          - 0
          - 16
          - 16
        -
          - 64
          - 0
          - 16
          - 16
        -
          - 80
          - 0
          - 16
          - 16
        -
          - 96
          - 0
          - 16
          - 16
        -
          - 112
          - 0
          - 16
          - 16
        -
          - 128
          - 0
          - 16
          - 16
        -
          - 144
          - 0
          - 16
          - 16
  Tiles: ~
  WallTorch:
    FireTorch:
      AnimSpeed: 5
      Clips:
        -
          - 0
          - 0
          - 16
          - 16
        -
          - 16
          - 0
          - 16
          - 16
        -
          - 32
          - 0
          - 16
          - 16
        -
          - 48
          - 0
          - 16
          - 16
        -
          - 64
          - 0
          - 16
          - 16
        -
          - 80
          - 0
          - 16
          - 16
        -
          - 96
          - 0
          - 16
          - 16
        -
          - 112
          - 0
          - 16
          - 16
  Monochrome:
    Idle:
      AnimSpeed: 5
      Clips:
        -
          - 0
          - 192
          - 16
          - 16
        -
          - 80
          - 192
          - 16
          - 16
    Run:
      AnimSpeed: 2
      Clips:
        -
          - 16
          - 192
          - 16
          - 16
        -
          - 32
          - 192
          - 16
          - 16
        -
          - 48
          - 192
          - 16
          - 16
        -
          - 64
          - 192
          - 16
          - 16
    Enemy_B:
      AnimSpeed: 5
      Clips:
        -
          - 0
          - 256
          - 16
          - 16
        -
          - 16
          - 256
          - 16
          - 16
        -
          - 32
          - 256
          - 16
          - 16
        -
          - 48
          - 256
          - 16
          - 16
    Enemy_D:
      AnimSpeed: 5
      Clips:
        -
          - 0
          - 272
          - 16
          - 16
        -
          - 16
          - 272
          - 16
          - 16
        -
          - 32
          - 272
          - 16
          - 16
        -
          - 48
          - 272
          - 16
          - 16
    Enemy_A:
      AnimSpeed: 5
      Clips:
        -
          - 0
          - 288
          - 16
          - 16
        -
          - 16
          - 288
          - 16
          - 16
        -
          - 32
          - 288
          - 16
          - 16
        -
          - 48
          - 288
          - 16
          - 16
    Enemy_C:
      AnimSpeed: 5
      Clips:
        -
          - 0
          - 304
          - 16
          - 16
        -
          - 16
          - 304
          - 16
          - 16
    Key:
      AnimSpeed: 5
      Clips:
        -
          - 256
          - 64
          - 16
          - 16
        -
          - 272
          - 64
          - 16
          - 16